#%RAML 0.8
---
title: "Muse: Mule Sales Enablement API"
documentation:
   title: Home
   content: |
         Welcome to the _Zencoder API_ Documentation. The _Zencoder API_
         allows you to connect your application to our encoding service
         and encode videos without going through the web  interface. You
         may also benefit from one of our
         [integration libraries](https://app.zencoder.com/docs/faq/basics/libraries)
         for different languages.
version: v1
schemas:
    - presentation: !include schema/presentation.json
      presentations: !include schema/presentations.json
      product: !include schema/product.json
      products: !include schema/products.json
securitySchemes: !include auth/security.yml
mediaType: application/json
baseUri: http://example.api.com/{version}
resourceTypes:
  - base:
      get?:
        responses: &standardResponses
          200:
            description: OK
      put?:
        responses: *standardResponses
      patch?:
        responses: *standardResponses
      post?:
          responses:
            201:
              description: Created
      delete?:
        responses: *standardResponses
  - collection:
      type: base
      get:
        is: [ paged ]
      post:
  - typedCollection:
      type: collection
      get:
        responses:
          200:
            body:
                schema: <<collectionSchema>>
      post:
        body:
            schema: <<itemSchema>>
        responses:
          201:
            body:
                schema: <<itemSchema>>
  - member:
      type: base
      get:
      put:
      patch:
      delete:
  - typedMember:
      type: member
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<itemSchema>>
                example: example/product.json
      put:
        body:
          application/json:
            schema: <<itemSchema>>
        responses:
          200:
            body:
              application/json:
                schema: <<itemSchema>>
      patch:
        body:
          application/json:
            schema: <<itemSchema>>
        responses:
          200:
            body:
              application/json:
                schema: <<itemSchema>>
      delete:
traits:
  - paged:
      queryParameters:
        start:
          displayName: start
          description: The first page to return
          type: integer
        pages:
          displayName: pages
          description: The number of pages to return
          type: integer
  - secured:
      headers:
        Authorization:
          description: The auth token for this request
      responses:
        401:
          description: Unauthorized
/presentations: &presentations
  displayName: Presentations
  type: { typedCollection: { itemSchema: presentation, collectionSchema: presentations } }
  securedBy: [jwt, oauth_2_0]
  get:
    description: This is get method
    queryParameters:
      title:
        type: string
        displayName: title
        description: Filter by title
  /{presentationId}:
    displayName: One presentation
    type: { typedMember: { itemSchema: presentation } }
    securedBy: [jwt]
/products:
  displayName: Products
  type: { typedCollection: { itemSchema: product, collectionSchema: products } }
  get:
    securedBy: [jwt, oauth_1_0]
    description: This is get method
    queryParameters:
      region:
        type: string
        displayName: region
        description: Filter by region
  /{productId}:
    displayName: One products
    type: { typedMember: { itemSchema: product } }
    get:
        securedBy: [jwt]
    put:
        securedBy: [jwt]
    patch:
        securedBy: [jwt]
    /presentations: *presentations
