#!/usr/bin/php -q

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \Cnam\Command\GenerateCommand());
$application->run();
