#!/usr/bin/php -q

<?php

function includeIfExists($file) {
  return file_exists($file) ? include $file : false;
}

if (!includeIfExists(__DIR__ . '/vendor/autoload.php') && !includeIfExists(__DIR__ . '/../../autoload.php')) {
  echo 'You must set up the project dependencies, run the following commands:'
       . PHP_EOL
       . 'curl -sS https://getcomposer.org/installer | php'
       . PHP_EOL
       . 'php composer.phar install'
       . PHP_EOL;
  exit(1);
}

use Symfony\Component\Console\Application;

$command = new \Cnam\Command\GenerateCommand();
$watch = new \Cnam\Command\WatchCommand();

$application = new Application('raml2html', '0.0.2');

$application->add($command);
$application->add($watch);
$application->setDefaultCommand($command->getName());
$application->run();
