- jwt:
    description: |
        Authorization with jwt usage header "X-HD-Access-Token" with token
    type: x-jwt
    describedBy:
        headers:
            X-HD-Access-Token:
                description: |
                   Valid jwt token
                example: |
                  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
        responses:
            401:
              description: |
                    Bad or expired token.
            403:
              description: |
                  Access denied not valid privilage in resurces
  oauth_2_0:
    description: |
        Dropbox supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
        headers:
            Authorization:
                description: |
                   Used to send a valid OAuth 2 access token. Do not use
                   with the "access_token" query string parameter.
                type: string
        queryParameters:
            access_token:
                description: |
                   Used to send a valid OAuth 2 access token. Do not use together with
                   the "Authorization" header
                type: string
        responses:
            401:
                description: |
                    Bad or expired token. This can happen if the user or Dropbox
                    revoked or expired an access token. To fix, you should re-
                    authenticate the user.
            403:
                description: |
                    Bad OAuth request (wrong consumer key, bad nonce, expired
                    timestamp...). Unfortunately, re-authenticating the user won't help here.
    settings:
        authorizationUri: https://www.dropbox.com/1/oauth2/authorize
        accessTokenUri: https://api.dropbox.com/1/oauth2/token
        authorizationGrants: [ code, token ]
  oauth_1_0:
    description: |
        OAuth 1.0 continues to be supported for all API requests, but OAuth 2.0 is now preferred.
    type: OAuth 1.0
    describedBy:
        responses:
            401:
                description: |
                    Bad or expired token. This can happen if the user or Dropbox
                    revoked or expired an access token. To fix, you should re-
                    authenticate the user.
            403:
                description: |
                    Bad OAuth request (wrong consumer key, bad nonce, expired
                    timestamp...). Unfortunately, re-authenticating the user won't help here.
    settings:
        requestTokenUri: https://api.dropbox.com/1/oauth/request_token
        authorizationUri: https://www.dropbox.com/1/oauth/authorize
        tokenCredentialsUri: https://api.dropbox.com/1/oauth/access_token
